spring.application.name=FenalBackend

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:5432/fenal
spring.datasource.username=${DB_USER:user}
spring.datasource.password=${DB_PASSWORD:password}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.spatial.dialect.postgis.PostgisPG10Dialect
spring.jpa.show-sql=true
spring.liquibase.enabled=false

fenal.aes.secret=MySuperSecretKeyForAES256But16
